[env:release]
platform = https://github.com/pioarduino/platform-espressif32
board = wemos_d1_mini32
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = huge_app.csv
build_flags = -w
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.3
    knolleary/PubSubClient@^2.8
    smougenot/TM1637
    ;olikraus/U8g2@^2.36.1
    thomasfredericks/Bounce2@^2.72
    ;tzapu/WiFiManager@^2.0.17

[env:dev]
extends = env:release
build_flags =
    ${env:release.build_flags}
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
    -D CONFIG_ARDUHAL_LOG_COLORS=1
build_type = debug

[env:wokwi]
extends = env:dev
board = az-delivery-devkit-v4
build_flags =
    ${env:dev.build_flags}
    -D WOKWI